version: '3.7'

networks:
  traefik:
    name: traefik-proxy
    driver: overlay
  monitoring:
    name: monitoring-network
    driver: overlay

configs:
  traefik-config:
    file: ./traefik.toml
  grafana-config:
    file: ./grafana.ini
  prometheus-config:
    file: ./prometheus.yml

volumes:
  traefik-logs: {}
  prometheus-data: {}
  grafana-data: {}
  grafana-profisioning-data: {}

services:
  reverse-proxy:
    image: traefik:v2.0
    depends_on:
      - traefik-proxy
      - monitoring-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-logs:/log
    deploy:
      mode: global
      labels:
        - traefik.http.routers.reverse-proxy.rule=Host(`server.mybid.lt`)
        - traefik.http.routers.reverse-proxy.tls=true
        - traefik.http.routers.reverse-proxy.tls.certresolver=le
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: traefik-config
        target: ./traefik.toml
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - traefik
      - monitoring

  prometheus:
    image: prom/prometheus
    depends_on:
      - reverse-proxy
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.external-url=http://localhost/prometheus'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    deploy:
      labels:
        - traefik.http.routers.prometheus.rule=Host(`server.mybid.lt`) && PathPrefix(`/prometheus`)
        - traefik.http.routers.prometheus.tls=true
        - traefik.http.routers.prometheus.tls.certresolver=le
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
      placement:
        constraints:
          - node.role==manager
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-profisioning-data:/etc/grafana/provisioning/
    command:
      - '--config=/etc/grafana/grafana.ini'
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.http.routers.grafana.rule=Host(`server.mybid.lt`) && PathPrefix(`/grafana`)
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=le
        - traefik.http.services.grafana.loadbalancer.server.port=3000
    configs:
      - source: grafana-config
        target: /etc/grafana/grafana.ini
    networks:
      - monitoring
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana