[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[providers]
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = true

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "error"
  filePath = "/log/traefik.log"

[accessLog]
  filePath = "/log/access.log"

[metrics]
  [metrics.prometheus]

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers.sample.acme]
  email = "aurimas.bachanovicius@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    entryPoint = "web"